/* eslint-disable camelcase */
interface IGeochemistryDTO {
  timestamp: string
  station_code: string
  ca_mg_l?: number
  na_mg_l?: number
  so4_mg_l?: number
  po4_mg_l?: number
  f_mg_l?: number
  al_mg_l?: number
  li_ug_l?: number
  v_ug_l?: number
  co_ug_l?: number
  zn_ug_l?: number
  zr_ug_l?: number
  ba_ug_l?: number
  sn_ug_l?: number
  pr_ug_l?: number
  eu_ug_l?: number
  dy_ug_l?: number
  yb_ug_l?: number
  mg_mg_l?: number
  hco3_mg_l?: number
  si_mg_l?: number
  sr_mg_l?: number
  cod_mg_l?: number
  cr_ug_l?: number
  ni_ug_l?: number
  as_ug_l?: number
  mo_ug_l?: number
  pb_ug_l?: number
  la_ug_l?: number
  nd_ug_l?: number
  gd_ug_l?: number
  ho_ug_l?: number
  lu_ug_l?: number
  k_mg_l?: number
  cl_mg_l?: number
  no3_mg_l?: number
  fe_mg_l?: number
  ti_ug_l?: number
  mn_ug_l?: number
  cu_ug_l?: number
  rb_ug_l?: number
  cd_ug_l?: number
  u_ug_l?: number
  ce_ug_l?: number
  sm_ug_l?: number
  tb_ug_l?: number
  er_ug_l?: number
  tm_ug_l?: number
}

interface IGeochemistryArraysDTO {
  ca_mg_l?: Array<any>
  na_mg_l?: Array<any>
  so4_mg_l?: Array<any>
  po4_mg_l?: Array<any>
  f_mg_l?: Array<any>
  al_mg_l?: Array<any>
  li_ug_l?: Array<any>
  v_ug_l?: Array<any>
  co_ug_l?: Array<any>
  zn_ug_l?: Array<any>
  zr_ug_l?: Array<any>
  ba_ug_l?: Array<any>
  sn_ug_l?: Array<any>
  pr_ug_l?: Array<any>
  eu_ug_l?: Array<any>
  dy_ug_l?: Array<any>
  yb_ug_l?: Array<any>
  mg_mg_l?: Array<any>
  hco3_mg_l?: Array<any>
  si_mg_l?: Array<any>
  sr_mg_l?: Array<any>
  cod_mg_l?: Array<any>
  cr_ug_l?: Array<any>
  ni_ug_l?: Array<any>
  as_ug_l?: Array<any>
  mo_ug_l?: Array<any>
  pb_ug_l?: Array<any>
  la_ug_l?: Array<any>
  nd_ug_l?: Array<any>
  gd_ug_l?: Array<any>
  ho_ug_l?: Array<any>
  lu_ug_l?: Array<any>
  k_mg_l?: Array<any>
  cl_mg_l?: Array<any>
  no3_mg_l?: Array<any>
  fe_mg_l?: Array<any>
  ti_ug_l?: Array<any>
  mn_ug_l?: Array<any>
  cu_ug_l?: Array<any>
  rb_ug_l?: Array<any>
  cd_ug_l?: Array<any>
  u_ug_l?: Array<any>
  ce_ug_l?: Array<any>
  sm_ug_l?: Array<any>
  tb_ug_l?: Array<any>
  er_ug_l?: Array<any>
  tm_ug_l?: Array<any>
}

export { IGeochemistryDTO, IGeochemistryArraysDTO }
