version: "3.7"

services: 
  app:    
    build: 
      context: ./
      dockerfile: dockerfile.dev
    container_name: ora-agua
    ports: 
      - 8080:8080
    volumes: 
      - .:/usr/app
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
